name = "Spike's Note"
description = "Spike's note and blog"
license = "MIT"
homepage = "https://github.com/st1020/kita"
min_version = "0.17.0"
demo = "https://st1020.github.io/kita/"

[author]
name = "st1020"
homepage = "https://st1020.com"

[original]
author = "nanxiaobei"
homepage = "https://lee.so/"
repo = "https://github.com/nanxiaobei/hugo-paper"
